#  calculator
# print(5+6)
# print(15-11)
# print(10 *4)
# print(15/6)
# print(5%3)
# print(2**4)
print("Welcome to chotu calculator")
print("Now you are going to give me two values and i will give all calculated values for it: ")
print("Give the value for a: ")
a=int(input())
print("Give the value for b: ")
b=int(input())
print("The value of  ", a ,"+",b ," is", a+b)
print("The value of ",a, "-" ,b, "is ",a-b)
print("The value of ",a, "*" ,b, "is ",a*b)
print("The value of ",a, "/" ,b, "is ",a/b)
print("The value of ",a, "**" ,b, "is ",a**b)
print("The value of ",a, "%" ,b, "is ",a%b)